name: Compile Examples

on:
  pull_request:
    paths:
      - ".github/workflows/compile-examples.yml"
      - "examples/**"
      - "src/**"
  push:
    paths:
      - ".github/workflows/compile-examples.yml"
      - "examples/**"
      - "src/**"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SKETCHES_REPORTS_PATH: sketches-reports
      LIBRARIES: |
        # Install the library from the local path.
        - source-path: ./

    strategy:
      fail-fast: false

      matrix:
        board:
          - fqbn: arduino:samd:nano_33_iot
            platforms: |
              - name: arduino:samd
          - fqbn: arduino:samd:arduino_zero_native
            platforms: |
              - name: arduino:samd
          - fqbn: arduino:samd:arduino_zero_edbg
            platforms: |
              - name: arduino:samd
          - fqbn: arduino:renesas_uno:minima
            platforms: |
              - name: arduino:renesas_uno
          - fqbn: arduino:renesas_uno:unor4wifi
            platforms: |
              - name: arduino:renesas_uno
          - fqbn: arduino:mbed_giga:giga
            platforms: |
              - name: arduino:mbed_giga

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile examples
        uses: arduino/compile-sketches@main
        with:
          fqbn: ${{ matrix.board.fqbn }}
          platforms: ${{ matrix.board.platforms }}
          libraries: ${{ env.LIBRARIES }}
          enable-deltas-report: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}
