name: Render Documentation

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/render-documentation.ya?ml"
      - "examples/**"
      - "src/**"
      - "!src/lib/**"
      - "!src/microchip/**"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/render-documentation.ya?ml"
      - "examples/**"
      - "src/**"
      - "!src/lib/**"
      - "!src/microchip/**"
  workflow_dispatch:
      
jobs:
  render-docs:
    permissions:
      contents: write
    uses: arduino/render-docs-github-action/.github/workflows/render-docs.yml@main
    with:
      source-path: './src'
      target-path: './docs/api.md'
      fail-on-warnings: false
      exclude-pattern: '*/lib/* */microchip/*'